import { useState } from 'react'
import { Activity, ArrowUpRight, BarChart3, Check, ChevronDown, CircleHelp, CloudDownload, Database, FileText, Filter, LayoutDashboard, MoreHorizontal, Plus, Search, Send, Settings2, Sparkles, Users, Zap } from 'lucide-react'
import './App.css'

function App() {
  const [query, setQuery] = useState('')
  const [submittedQuery, setSubmittedQuery] = useState('Show me overdue Jira issues by team')
  const [activeNav, setActiveNav] = useState('Overview')
  const submitQuery = () => { if (query.trim()) { setSubmittedQuery(query.trim()); setQuery('') } }
  const navItems = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Ask data', icon: Sparkles }, { label: 'Dashboards', icon: BarChart3 }, { label: 'Exports', icon: CloudDownload }]

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Sparkles size={16} /></span><span>signal<span className="brand-dot">.</span></span></div>
      <div className="workspace-switcher"><span className="workspace-avatar">N</span><span><strong>Northstar team</strong><small>Workspace</small></span><ChevronDown size={14} /></div>
      <nav className="nav-list"><p className="nav-label">Workspace</p>{navItems.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setActiveNav(label)}><Icon size={17} />{label}{label === 'Ask data' && <span className="nav-kbd">⌘ K</span>}</button>)}<p className="nav-label">Manage</p><button className="nav-item"><Database size={17} />Connections<span className="nav-count">3</span></button><button className="nav-item"><Settings2 size={17} />Settings</button></nav>
      <div className="sidebar-bottom"><div className="usage"><div><span>Sync capacity</span><strong>72%</strong></div><div className="usage-bar"><span /></div><small>Resets in 12 days</small></div><div className="user-row"><div className="user-avatar">AM</div><span><strong>Alex Morgan</strong><small>Admin</small></span><MoreHorizontal size={17} /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="breadcrumbs"><span>Northstar team</span><span>/</span><strong>{activeNav}</strong></div><div className="top-actions"><button className="icon-button" title="Help"><CircleHelp size={18} /></button><button className="icon-button" title="Search"><Search size={18} /></button><button className="primary-button"><Plus size={16} /> Add connection</button></div></header>
      <div className="page-content">
        <section className="intro"><div><p className="eyebrow"><Activity size={14} /> LIVE WORKSPACE</p><h1>Good morning, Alex</h1><p className="subheading">Your connected work, distilled into decisions.</p></div><button className="date-button">Last 30 days <ChevronDown size={15} /></button></section>
        <section className="ask-panel"><div className="ask-heading"><span className="sparkle-icon"><Sparkles size={17} /></span><div><h2>Ask your workspace</h2><p>Query Jira, Asana, and more in plain language.</p></div><span className="beta-tag">BETA</span></div><div className="query-input"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && submitQuery()} placeholder="e.g. Which projects are at risk this month?" /><button onClick={submitQuery}><Send size={16} /></button></div><div className="query-suggestion"><Zap size={13} /> Recent query: <span>{submittedQuery}</span><ArrowUpRight size={13} /></div></section>
        <section className="metric-grid"><Metric icon={<Check size={18} />} label="Tasks completed" value="428" change="+18.4%" detail="vs. previous period" tone="green" /><Metric icon={<Activity size={18} />} label="Open work" value="164" change="-6.2%" detail="vs. previous period" tone="blue" /><Metric icon={<Users size={18} />} label="Active contributors" value="32" change="+4" detail="this month" tone="orange" /><Metric icon={<FileText size={18} />} label="Data freshness" value="12 min" change="Healthy" detail="last sync" tone="purple" /></section>
        <section className="dashboard-grid"><div className="panel chart-panel"><div className="panel-header"><div><h2>Work completed</h2><p>Across all connected sources</p></div><div className="panel-actions"><button className="filter-button"><Filter size={14} /> Filter</button><button className="icon-button"><MoreHorizontal size={17} /></button></div></div><div className="chart-legend"><span><i className="legend-dot teal" /> Completed</span><span><i className="legend-dot coral" /> Created</span></div><div className="chart"><div className="chart-y"><span>200</span><span>150</span><span>100</span><span>50</span><span>0</span></div><div className="chart-area"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 700 220" preserveAspectRatio="none" aria-label="Work completed chart"><path className="area-fill" d="M0,185 C45,160 70,170 105,140 S165,118 205,145 S270,155 310,103 S375,128 420,89 S480,112 520,67 S590,92 640,41 S685,61 700,30 L700,220 L0,220Z" /><path className="line teal-line" d="M0,185 C45,160 70,170 105,140 S165,118 205,145 S270,155 310,103 S375,128 420,89 S480,112 520,67 S590,92 640,41 S685,61 700,30" /><path className="line coral-line" d="M0,202 C55,184 82,190 120,173 S180,162 218,179 S282,170 325,148 S388,155 430,128 S486,145 530,117 S595,127 640,102 S682,110 700,89" /></svg><div className="chart-x"><span>Aug 23</span><span>Aug 30</span><span>Sep 06</span><span>Sep 13</span><span>Sep 20</span></div></div></div></div><div className="right-stack"><div className="panel source-panel"><div className="panel-header"><div><h2>Connected sources</h2><p>Sync status at a glance</p></div><button className="icon-button"><Plus size={17} /></button></div><SourceRow name="Jira Software" meta="Last synced 12 min ago" color="jira" /><SourceRow name="Asana" meta="Last synced 18 min ago" color="asana" /><SourceRow name="Linear" meta="Last synced 1 hr ago" color="linear" /><button className="view-all">Manage connections <ArrowUpRight size={14} /></button></div><div className="panel insight-panel"><div className="insight-icon"><Sparkles size={18} /></div><div><p className="eyebrow">AI INSIGHT</p><h3>Delivery pace is up 18% this month</h3><p>Frontend and Platform teams are driving the change.</p></div><button className="icon-button"><ArrowUpRight size={16} /></button></div></div></section>
      </div>
    </main>
  </div>
}

function Metric({ icon, label, value, change, detail, tone }: { icon: React.ReactNode; label: string; value: string; change: string; detail: string; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small className={tone === 'green' || tone === 'blue' ? 'positive' : ''}>{change} <em>{detail}</em></small></div></div> }
function SourceRow({ name, meta, color }: { name: string; meta: string; color: string }) { return <div className="source-row"><span className={`source-logo ${color}`}>{name[0]}</span><span><strong>{name}</strong><small>{meta}</small></span><span className="status-dot" /></div> }
export default App
